### ISSUE TITLE
Plugin does not work with deprecated / renamed icons

### ISSUE THREAD

**Issue by rbozan** [WarningImHack3r/vite-plugin-lucide-preprocess#5]
### What is the issue?

It does not work with deprecated or renamed icons. For example:

`<PlayCircle>`
`<HelpCircleIcon>`
`<MoreVerticalIcon>`

These all work in lucide-svelte but not if you are using this plugin.

### What are the steps to reproduce this issue?

Import the module, install the plugin, check if the build works	

### What were you expecting to happen?

It would build

### What OS are you experiencing the problem on?

Linux

### Duplicates

- [X] I have checked that my problem has not already been mentioned recently in an existing issue

**Comment by WarningImHack3r** [comment]
Thanks for reporting; I'll take a look!

**Comment by WarningImHack3r** [comment]
Update: I can confirm that deprecated or renamed icons can indeed cause problems.

The problem is that I have no way of knowing if the icon file has been renamed: I'm simply reading imports in as strings and manipulating those to fall upon a working import, I don't do _any_ static analysis on them.
This means I can't check whether an import is correct nor dynamically ask the LSP for the matching package.

I'm not really sure how I'm supposed to handle this situation, though... The only thing I could think of would be hardcoding exclusions in my code, which obviously isn't the best solution.

**Comment by WarningImHack3r** [comment]
Update 2: I can reliably create a map of renamings from my tests, then automatically push an update on NPM if it fails with the new contents.

It's still hacky, but doable in an end-to-end automatic way. You'd just have to bump your NPM version of the plugin once a breaking change (renaming) is introduced by Lucide, and everything’d work.

I'm still very much welcome to a better solution, though
